-- PS Data Exporter - Installation SQL
-- Compatible PrestaShop 1.7.6.5+ / PHP 7.2+

-- Table des jobs d'export
CREATE TABLE IF NOT EXISTS `PREFIX_pde_export_job` (
    `id_export_job` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    `id_employee` INT(11) UNSIGNED NOT NULL,
    `id_shop` INT(11) UNSIGNED DEFAULT NULL,
    `export_type` VARCHAR(32) NOT NULL DEFAULT 'orders' COMMENT 'customers|orders|full',
    `export_level` VARCHAR(32) NOT NULL DEFAULT 'essential' COMMENT 'essential|complete|ultra',
    `export_mode` VARCHAR(32) NOT NULL DEFAULT 'relational' COMMENT 'relational|flat',
    `params_json` LONGTEXT NOT NULL COMMENT 'Filtres et options JSON',
    `schema_snapshot` LONGTEXT DEFAULT NULL COMMENT 'Snapshot colonnes au démarrage',
    `status` VARCHAR(32) NOT NULL DEFAULT 'pending' COMMENT 'pending|running|paused|completed|failed',
    `total_records` INT(11) UNSIGNED DEFAULT 0,
    `processed_records` INT(11) UNSIGNED DEFAULT 0,
    `current_entity` VARCHAR(64) DEFAULT NULL,
    `cursors_json` TEXT DEFAULT NULL COMMENT 'Curseurs par entité JSON',
    `error_message` TEXT DEFAULT NULL,
    `started_at` DATETIME DEFAULT NULL,
    `completed_at` DATETIME DEFAULT NULL,
    `date_add` DATETIME NOT NULL,
    `date_upd` DATETIME NOT NULL,
    PRIMARY KEY (`id_export_job`),
    KEY `idx_status` (`status`),
    KEY `idx_employee` (`id_employee`),
    KEY `idx_date_add` (`date_add`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table des fichiers générés
CREATE TABLE IF NOT EXISTS `PREFIX_pde_export_file` (
    `id_export_file` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    `id_export_job` INT(11) UNSIGNED NOT NULL,
    `entity_name` VARCHAR(64) NOT NULL,
    `filepath` VARCHAR(512) NOT NULL,
    `filename` VARCHAR(255) NOT NULL,
    `filesize` BIGINT UNSIGNED DEFAULT 0,
    `row_count` INT(11) UNSIGNED DEFAULT 0,
    `checksum` VARCHAR(64) DEFAULT NULL,
    `download_token` VARCHAR(64) NOT NULL,
    `download_expires` DATETIME NOT NULL,
    `download_count` INT(11) UNSIGNED DEFAULT 0,
    `date_add` DATETIME NOT NULL,
    PRIMARY KEY (`id_export_file`),
    KEY `idx_job` (`id_export_job`),
    KEY `idx_token` (`download_token`),
    KEY `idx_expires` (`download_expires`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table de mapping géographique France (département -> région)
CREATE TABLE IF NOT EXISTS `PREFIX_pde_geo_map` (
    `id_geo_map` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    `country_iso` VARCHAR(3) NOT NULL DEFAULT 'FR',
    `dept_code` VARCHAR(5) NOT NULL,
    `dept_name` VARCHAR(128) NOT NULL,
    `region_code` VARCHAR(5) NOT NULL,
    `region_name` VARCHAR(128) NOT NULL,
    PRIMARY KEY (`id_geo_map`),
    UNIQUE KEY `idx_dept` (`country_iso`, `dept_code`),
    KEY `idx_region` (`region_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Insertion des départements français
INSERT INTO `PREFIX_pde_geo_map` (`country_iso`, `dept_code`, `dept_name`, `region_code`, `region_name`) VALUES
('FR', '01', 'Ain', 'ARA', 'Auvergne-Rhône-Alpes'),
('FR', '02', 'Aisne', 'HDF', 'Hauts-de-France'),
('FR', '03', 'Allier', 'ARA', 'Auvergne-Rhône-Alpes'),
('FR', '04', 'Alpes-de-Haute-Provence', 'PAC', 'Provence-Alpes-Côte d''Azur'),
('FR', '05', 'Hautes-Alpes', 'PAC', 'Provence-Alpes-Côte d''Azur'),
('FR', '06', 'Alpes-Maritimes', 'PAC', 'Provence-Alpes-Côte d''Azur'),
('FR', '07', 'Ardèche', 'ARA', 'Auvergne-Rhône-Alpes'),
('FR', '08', 'Ardennes', 'GES', 'Grand Est'),
('FR', '09', 'Ariège', 'OCC', 'Occitanie'),
('FR', '10', 'Aube', 'GES', 'Grand Est'),
('FR', '11', 'Aude', 'OCC', 'Occitanie'),
('FR', '12', 'Aveyron', 'OCC', 'Occitanie'),
('FR', '13', 'Bouches-du-Rhône', 'PAC', 'Provence-Alpes-Côte d''Azur'),
('FR', '14', 'Calvados', 'NOR', 'Normandie'),
('FR', '15', 'Cantal', 'ARA', 'Auvergne-Rhône-Alpes'),
('FR', '16', 'Charente', 'NAQ', 'Nouvelle-Aquitaine'),
('FR', '17', 'Charente-Maritime', 'NAQ', 'Nouvelle-Aquitaine'),
('FR', '18', 'Cher', 'CVL', 'Centre-Val de Loire'),
('FR', '19', 'Corrèze', 'NAQ', 'Nouvelle-Aquitaine'),
('FR', '21', 'Côte-d''Or', 'BFC', 'Bourgogne-Franche-Comté'),
('FR', '22', 'Côtes-d''Armor', 'BRE', 'Bretagne'),
('FR', '23', 'Creuse', 'NAQ', 'Nouvelle-Aquitaine'),
('FR', '24', 'Dordogne', 'NAQ', 'Nouvelle-Aquitaine'),
('FR', '25', 'Doubs', 'BFC', 'Bourgogne-Franche-Comté'),
('FR', '26', 'Drôme', 'ARA', 'Auvergne-Rhône-Alpes'),
('FR', '27', 'Eure', 'NOR', 'Normandie'),
('FR', '28', 'Eure-et-Loir', 'CVL', 'Centre-Val de Loire'),
('FR', '29', 'Finistère', 'BRE', 'Bretagne'),
('FR', '2A', 'Corse-du-Sud', 'COR', 'Corse'),
('FR', '2B', 'Haute-Corse', 'COR', 'Corse'),
('FR', '30', 'Gard', 'OCC', 'Occitanie'),
('FR', '31', 'Haute-Garonne', 'OCC', 'Occitanie'),
('FR', '32', 'Gers', 'OCC', 'Occitanie'),
('FR', '33', 'Gironde', 'NAQ', 'Nouvelle-Aquitaine'),
('FR', '34', 'Hérault', 'OCC', 'Occitanie'),
('FR', '35', 'Ille-et-Vilaine', 'BRE', 'Bretagne'),
('FR', '36', 'Indre', 'CVL', 'Centre-Val de Loire'),
('FR', '37', 'Indre-et-Loire', 'CVL', 'Centre-Val de Loire'),
('FR', '38', 'Isère', 'ARA', 'Auvergne-Rhône-Alpes'),
('FR', '39', 'Jura', 'BFC', 'Bourgogne-Franche-Comté'),
('FR', '40', 'Landes', 'NAQ', 'Nouvelle-Aquitaine'),
('FR', '41', 'Loir-et-Cher', 'CVL', 'Centre-Val de Loire'),
('FR', '42', 'Loire', 'ARA', 'Auvergne-Rhône-Alpes'),
('FR', '43', 'Haute-Loire', 'ARA', 'Auvergne-Rhône-Alpes'),
('FR', '44', 'Loire-Atlantique', 'PDL', 'Pays de la Loire'),
('FR', '45', 'Loiret', 'CVL', 'Centre-Val de Loire'),
('FR', '46', 'Lot', 'OCC', 'Occitanie'),
('FR', '47', 'Lot-et-Garonne', 'NAQ', 'Nouvelle-Aquitaine'),
('FR', '48', 'Lozère', 'OCC', 'Occitanie'),
('FR', '49', 'Maine-et-Loire', 'PDL', 'Pays de la Loire'),
('FR', '50', 'Manche', 'NOR', 'Normandie'),
('FR', '51', 'Marne', 'GES', 'Grand Est'),
('FR', '52', 'Haute-Marne', 'GES', 'Grand Est'),
('FR', '53', 'Mayenne', 'PDL', 'Pays de la Loire'),
('FR', '54', 'Meurthe-et-Moselle', 'GES', 'Grand Est'),
('FR', '55', 'Meuse', 'GES', 'Grand Est'),
('FR', '56', 'Morbihan', 'BRE', 'Bretagne'),
('FR', '57', 'Moselle', 'GES', 'Grand Est'),
('FR', '58', 'Nièvre', 'BFC', 'Bourgogne-Franche-Comté'),
('FR', '59', 'Nord', 'HDF', 'Hauts-de-France'),
('FR', '60', 'Oise', 'HDF', 'Hauts-de-France'),
('FR', '61', 'Orne', 'NOR', 'Normandie'),
('FR', '62', 'Pas-de-Calais', 'HDF', 'Hauts-de-France'),
('FR', '63', 'Puy-de-Dôme', 'ARA', 'Auvergne-Rhône-Alpes'),
('FR', '64', 'Pyrénées-Atlantiques', 'NAQ', 'Nouvelle-Aquitaine'),
('FR', '65', 'Hautes-Pyrénées', 'OCC', 'Occitanie'),
('FR', '66', 'Pyrénées-Orientales', 'OCC', 'Occitanie'),
('FR', '67', 'Bas-Rhin', 'GES', 'Grand Est'),
('FR', '68', 'Haut-Rhin', 'GES', 'Grand Est'),
('FR', '69', 'Rhône', 'ARA', 'Auvergne-Rhône-Alpes'),
('FR', '70', 'Haute-Saône', 'BFC', 'Bourgogne-Franche-Comté'),
('FR', '71', 'Saône-et-Loire', 'BFC', 'Bourgogne-Franche-Comté'),
('FR', '72', 'Sarthe', 'PDL', 'Pays de la Loire'),
('FR', '73', 'Savoie', 'ARA', 'Auvergne-Rhône-Alpes'),
('FR', '74', 'Haute-Savoie', 'ARA', 'Auvergne-Rhône-Alpes'),
('FR', '75', 'Paris', 'IDF', 'Île-de-France'),
('FR', '76', 'Seine-Maritime', 'NOR', 'Normandie'),
('FR', '77', 'Seine-et-Marne', 'IDF', 'Île-de-France'),
('FR', '78', 'Yvelines', 'IDF', 'Île-de-France'),
('FR', '79', 'Deux-Sèvres', 'NAQ', 'Nouvelle-Aquitaine'),
('FR', '80', 'Somme', 'HDF', 'Hauts-de-France'),
('FR', '81', 'Tarn', 'OCC', 'Occitanie'),
('FR', '82', 'Tarn-et-Garonne', 'OCC', 'Occitanie'),
('FR', '83', 'Var', 'PAC', 'Provence-Alpes-Côte d''Azur'),
('FR', '84', 'Vaucluse', 'PAC', 'Provence-Alpes-Côte d''Azur'),
('FR', '85', 'Vendée', 'PDL', 'Pays de la Loire'),
('FR', '86', 'Vienne', 'NAQ', 'Nouvelle-Aquitaine'),
('FR', '87', 'Haute-Vienne', 'NAQ', 'Nouvelle-Aquitaine'),
('FR', '88', 'Vosges', 'GES', 'Grand Est'),
('FR', '89', 'Yonne', 'BFC', 'Bourgogne-Franche-Comté'),
('FR', '90', 'Territoire de Belfort', 'BFC', 'Bourgogne-Franche-Comté'),
('FR', '91', 'Essonne', 'IDF', 'Île-de-France'),
('FR', '92', 'Hauts-de-Seine', 'IDF', 'Île-de-France'),
('FR', '93', 'Seine-Saint-Denis', 'IDF', 'Île-de-France'),
('FR', '94', 'Val-de-Marne', 'IDF', 'Île-de-France'),
('FR', '95', 'Val-d''Oise', 'IDF', 'Île-de-France'),
('FR', '971', 'Guadeloupe', 'GUA', 'Guadeloupe'),
('FR', '972', 'Martinique', 'MTQ', 'Martinique'),
('FR', '973', 'Guyane', 'GUF', 'Guyane'),
('FR', '974', 'La Réunion', 'REU', 'La Réunion'),
('FR', '976', 'Mayotte', 'MAY', 'Mayotte');

-- Table des logs d'export (sans PII)
CREATE TABLE IF NOT EXISTS `PREFIX_pde_export_log` (
    `id_log` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    `id_export_job` INT(11) UNSIGNED NOT NULL,
    `level` VARCHAR(16) NOT NULL DEFAULT 'info' COMMENT 'debug|info|warning|error',
    `message` TEXT NOT NULL,
    `context_json` TEXT DEFAULT NULL,
    `date_add` DATETIME NOT NULL,
    PRIMARY KEY (`id_log`),
    KEY `idx_job` (`id_export_job`),
    KEY `idx_level` (`level`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
